// <auto-generated />
namespace SignalRChat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DbMigrate3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbMigrate3));
        
        string IMigrationMetadata.Id
        {
            get { return "201710131216150_DbMigrate3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
